version: "3.9"

services:
  koa:
    image: koa-img
    build:
      context: ./koa
    user: "node"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - ./koa:/node/koa
      - ./koa/node_modules:/node/node_modules
    expose:
      - 3000
    # command: node index.js
    command: ./node_modules/pm2/bin/pm2-runtime index.js --no-daemon
    depends_on:
      db:
        condition: service_healthy

  sinatra:
    image: ruby-img
    build:
      context: ./sinatra
    env_file:
      - .env
    ports:
      - 9000:9292
    expose:
      - 9000
    volumes:
      - ./sinatra:/app:ro
    depends_on:
      db:
        condition: service_healthy
    #  stdin_open: true
    #  tty: true
    restart: on-failure
    #  command: ["./initializers/wait-for-pg.sh", "db", "rackup"]

  db:
    image: db-img
    build:
      context: .
    env_file:
      - .env
    ports:
      - 5000:5432
    container_name: db-cont
    volumes:
      - db-vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1 "]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-vol:
